# ===========================================
# Prometheus 云服务器监控配置
# ===========================================
# 针对 SaaS Control Deck 全栈AI平台优化

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s
  external_labels:
    cluster: 'saascontrol-cloud'
    environment: 'production'

# 告警规则文件
rule_files:
  - "/etc/prometheus/rules/*.yml"

# 告警管理器配置
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['localhost:9093']

# 服务发现和监控目标配置
scrape_configs:
  
  # ===========================================
  # 系统监控
  # ===========================================
  
  # Prometheus自监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s
    metrics_path: '/metrics'

  # Node Exporter - 系统指标
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
    scrape_interval: 10s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'cloud-server-main'

  # ===========================================
  # 应用服务监控
  # ===========================================
  
  # 前端服务监控 - Next.js
  - job_name: 'frontend-app'
    static_configs:
      - targets: ['frontend-app:3000']
    scrape_interval: 30s
    metrics_path: '/api/metrics'
    timeout: 10s
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: 'frontend'
      - source_labels: [__address__]
        target_label: component
        replacement: 'nextjs-app'

  # Backend Pro1 - API Gateway
  - job_name: 'api-gateway-pro1'
    static_configs:
      - targets: ['api-gateway-pro1:8000']
    scrape_interval: 15s
    metrics_path: '/metrics'
    timeout: 10s
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: 'api-gateway'
      - source_labels: [__address__]
        target_label: project
        replacement: 'pro1'

  # Backend Pro1 - Data Service
  - job_name: 'data-service-pro1'
    static_configs:
      - targets: ['data-service-pro1:8001']
    scrape_interval: 15s
    metrics_path: '/metrics'
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: 'data-service'
      - source_labels: [__address__]
        target_label: project
        replacement: 'pro1'

  # Backend Pro1 - AI Service
  - job_name: 'ai-service-pro1'
    static_configs:
      - targets: ['ai-service-pro1:8002']
    scrape_interval: 15s
    metrics_path: '/metrics'
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: 'ai-service'
      - source_labels: [__address__]
        target_label: project
        replacement: 'pro1'

  # Backend Pro2 - API Gateway
  - job_name: 'api-gateway-pro2'
    static_configs:
      - targets: ['api-gateway-pro2:8100']
    scrape_interval: 15s
    metrics_path: '/metrics'
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: 'api-gateway'
      - source_labels: [__address__]
        target_label: project
        replacement: 'pro2'

  # Backend Pro2 - Data Service
  - job_name: 'data-service-pro2'
    static_configs:
      - targets: ['data-service-pro2:8101']
    scrape_interval: 15s
    metrics_path: '/metrics'
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: 'data-service'
      - source_labels: [__address__]
        target_label: project
        replacement: 'pro2'

  # Backend Pro2 - AI Service
  - job_name: 'ai-service-pro2'
    static_configs:
      - targets: ['ai-service-pro2:8102']
    scrape_interval: 15s
    metrics_path: '/metrics'
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: 'ai-service'
      - source_labels: [__address__]
        target_label: project
        replacement: 'pro2'

  # ===========================================
  # 数据存储监控
  # ===========================================
  
  # PostgreSQL监控
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: 'postgresql'
      - source_labels: [__address__]
        target_label: database_type
        replacement: 'primary'

  # Redis监控
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: 'redis'
      - source_labels: [__address__]
        target_label: cache_type
        replacement: 'primary'

  # MinIO监控
  - job_name: 'minio-metrics'
    static_configs:
      - targets: ['minio-storage:9000']
    scrape_interval: 30s
    metrics_path: '/minio/v2/metrics/cluster'
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: 'minio'
      - source_labels: [__address__]
        target_label: storage_type
        replacement: 'object-store'

  # ===========================================
  # 容器和基础设施监控
  # ===========================================
  
  # Docker容器监控 - cAdvisor
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: 'docker-containers'

  # Docker daemon监控
  - job_name: 'docker-daemon'
    static_configs:
      - targets: ['localhost:9323']
    scrape_interval: 30s
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: 'docker-daemon'

  # ===========================================
  # AI和分布式计算监控
  # ===========================================
  
  # Ray集群监控
  - job_name: 'ray-cluster'
    static_configs:
      - targets: ['ray-cluster:8265']
    scrape_interval: 30s
    metrics_path: '/api/v0/metrics'
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: 'ray-compute'
      - source_labels: [__address__]
        target_label: cluster_type
        replacement: 'head-node'

  # OpenAI API监控 (自定义指标)
  - job_name: 'openai-metrics'
    static_configs:
      - targets: ['ai-service-pro1:8002', 'ai-service-pro2:8102']
    scrape_interval: 60s
    metrics_path: '/metrics/openai'
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: 'openai-integration'

  # ===========================================
  # Web服务和代理监控
  # ===========================================
  
  # Nginx监控
  - job_name: 'nginx-exporter'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 30s
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: 'nginx'
      - source_labels: [__address__]
        target_label: proxy_type
        replacement: 'reverse-proxy'

  # ===========================================
  # 日志和搜索系统监控
  # ===========================================
  
  # Elasticsearch监控
  - job_name: 'elasticsearch-exporter'
    static_configs:
      - targets: ['elasticsearch-exporter:9114']
    scrape_interval: 60s
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: 'elasticsearch'
      - source_labels: [__address__]
        target_label: search_type
        replacement: 'logging'

  # ===========================================
  # 健康检查监控
  # ===========================================
  
  # 服务健康检查
  - job_name: 'health-checks'
    static_configs:
      - targets: ['frontend-app:3000', 'api-gateway-pro1:8000', 'api-gateway-pro2:8100']
    scrape_interval: 30s
    metrics_path: '/health'
    relabel_configs:
      - source_labels: [__address__]
        target_label: check_type
        replacement: 'service-health'

  # ===========================================
  # 业务指标监控
  # ===========================================
  
  # 用户活动指标
  - job_name: 'business-metrics-users'
    static_configs:
      - targets: ['api-gateway-pro1:8000', 'api-gateway-pro2:8100']
    scrape_interval: 120s
    metrics_path: '/metrics/business/users'
    relabel_configs:
      - source_labels: [__address__]
        target_label: metric_type
        replacement: 'user-activity'

  # AI使用指标
  - job_name: 'business-metrics-ai'
    static_configs:
      - targets: ['ai-service-pro1:8002', 'ai-service-pro2:8102']
    scrape_interval: 60s
    metrics_path: '/metrics/business/ai'
    relabel_configs:
      - source_labels: [__address__]
        target_label: metric_type
        replacement: 'ai-usage'

  # 性能指标
  - job_name: 'business-metrics-performance'
    static_configs:
      - targets: ['api-gateway-pro1:8000', 'api-gateway-pro2:8100']
    scrape_interval: 30s
    metrics_path: '/metrics/business/performance'
    relabel_configs:
      - source_labels: [__address__]
        target_label: metric_type
        replacement: 'performance'

# ===========================================
# 远程写入配置 (可选)
# ===========================================
# remote_write:
#   - url: 'https://prometheus-remote-write.example.com/api/v1/write'
#     basic_auth:
#       username: 'prometheus'
#       password: 'your_password'
#     queue_config:
#       capacity: 2500
#       max_shards: 200
#       min_shards: 1
#       max_samples_per_send: 500
#       batch_send_deadline: 5s
#       min_backoff: 30ms
#       max_backoff: 100ms

# ===========================================
# 存储配置
# ===========================================
# 保留30天数据，每2小时压缩一次
# storage.tsdb.retention.time=30d
# storage.tsdb.retention.size=50GB