global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    environment: staging
    cluster: saascontroldeck-staging

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Frontend Staging
  - job_name: 'frontend-staging'
    static_configs:
      - targets: ['frontend-staging:3000']
    metrics_path: '/api/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Backend Pro1 Staging
  - job_name: 'backend-pro1-staging'
    static_configs:
      - targets: ['backend-pro1-staging:8000']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Backend Pro2 Staging
  - job_name: 'backend-pro2-staging'
    static_configs:
      - targets: ['backend-pro2-staging:8100']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Database Monitoring
  - job_name: 'postgres-staging'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Redis Monitoring
  - job_name: 'redis-staging'
    static_configs:
      - targets: ['redis-exporter:9121']

  # MinIO Monitoring
  - job_name: 'minio-staging'
    static_configs:
      - targets: ['minio-staging:9000']
    metrics_path: '/minio/v2/metrics/cluster'

  # Node Exporter (System Metrics)
  - job_name: 'node-exporter-staging'
    static_configs:
      - targets: ['node-exporter:9100']

  # cAdvisor (Container Metrics)
  - job_name: 'cadvisor-staging'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s

  # Nginx Metrics
  - job_name: 'nginx-staging'
    static_configs:
      - targets: ['nginx-exporter:9113']

  # Blackbox Exporter (External Health Checks)
  - job_name: 'blackbox-staging'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://staging.saascontroldeck.com
        - https://staging.saascontroldeck.com/api/health
        - https://staging.saascontroldeck.com/api/pro1/health
        - https://staging.saascontroldeck.com/api/pro2/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115