# GitHub Environment: Production
# 用于生产环境的配置

name: production
description: 生产环境配置

# 严格保护规则
protection_rules:
  wait_timer: 300  # 5分钟等待时间
  reviewers:
    - type: user
      id: # 替换为实际的GitHub用户ID
    - type: team
      id: # 替换为实际的团队ID
  prevent_self_review: true
  required_reviewers: 1

# 部署分支限制
deployment_branch_policy:
  protected_branches: true
  custom_branch_policies: false

# 环境变量
variables:
  ENVIRONMENT: production
  LOG_LEVEL: INFO
  FRONTEND_URL: https://saascontroldeck.com
  BACKEND_URL: https://api.saascontroldeck.com
  
  # Node.js生产配置
  NODE_ENV: production
  NODE_VERSION: '18'
  NEXT_TELEMETRY_DISABLED: '1'
  
  # Python生产配置
  PYTHON_VERSION: '3.11'
  PYTHONPATH: /app
  PYTHONUNBUFFERED: '1'
  
  # 数据库生产配置
  DB_POOL_SIZE: '20'
  DB_MAX_OVERFLOW: '30'
  DB_POOL_RECYCLE: '3600'
  
  # Redis生产配置
  REDIS_MAX_CONNECTIONS: '50'
  REDIS_RETRY_ON_TIMEOUT: 'true'
  
  # AI服务生产配置
  AI_MODEL_TIMEOUT: '60'
  RAY_WORKER_COUNT: '8'
  RAY_MEMORY_LIMIT: '8GB'
  
  # 安全配置
  SECURE_SSL_REDIRECT: 'true'
  SESSION_COOKIE_SECURE: 'true'
  CSRF_COOKIE_SECURE: 'true'
  
  # 性能配置
  GUNICORN_WORKERS: '4'
  GUNICORN_THREADS: '2'
  GUNICORN_TIMEOUT: '30'
  
  # 监控配置
  PROMETHEUS_ENABLED: 'true'
  METRICS_ENABLED: 'true'
  HEALTH_CHECK_INTERVAL: '30'

# 生产密钥配置
secrets:
  # 核心安全
  - SECRET_KEY  # 强密钥，至少32字符
  - DATABASE_URL  # 生产数据库连接
  - REDIS_URL  # 生产Redis连接
  
  # 第三方服务
  - OPENAI_API_KEY  # OpenAI生产密钥
  - SENTRY_DSN  # 生产Sentry配置
  
  # SSL/TLS证书
  - SSL_CERT_PATH  # SSL证书路径
  - SSL_KEY_PATH  # SSL私钥路径
  
  # 容器注册表
  - DOCKER_REGISTRY  # 生产注册表
  - DOCKER_USERNAME  # 注册表用户名
  - DOCKER_PASSWORD  # 注册表密码
  
  # 部署令牌
  - DEPLOY_WEBHOOK_URL  # 部署回调URL
  - DEPLOY_TOKEN  # 部署认证令牌
  
  # 监控和日志
  - PROMETHEUS_AUTH  # Prometheus认证
  - GRAFANA_API_KEY  # Grafana API密钥
  
  # 备份和恢复
  - BACKUP_ACCESS_KEY  # 备份存储密钥
  - BACKUP_SECRET_KEY  # 备份存储密钥